excerpt_separator: ""
highlighter: true
markdown: kramdown
url: https://javascript.sg
title: KahWee Teng
tagline: A log of everyday life
description: My awesome new site
paginate: 5
gems: [jekyll-paginate, jekyll-assets]
sass:
    sass_dir: _sass